// Moteur SKU produit — règles du CDC (docs/specs/CDC_calcul_SKU.docx).
// Format : [MODÈLE][ANNÉE][SAISON]-[MATIÈRE][OPTION]-[COULEUR]
// Exemple : AA002 + 26 + E + CU002 + 01 + 001  ->  AA00226E-CU00201-001

export interface SkuComponents {
  modelId: string; // ex. "AA002"
  yearId: string; // 2 chiffres, ex. "26"
  seasonId: string; // "H" | "E"
  materialId: string; // ex. "CU002" / "CE001"
  optionId: string; // 2 chiffres, ex. "01"
  colorId: string; // 3 chiffres, ex. "001" / "999"
}

/** Assemble le SKU final à partir des composants (formatage option/saison/casse). */
export function assembleSku(c: SkuComponents): string {
  const model = (c.modelId || 'AA000').toUpperCase();
  const year = (c.yearId || '25').padStart(2, '0');
  const season = (c.seasonId || 'H').toUpperCase();
  const material = (c.materialId || 'CU000').toUpperCase();
  const option = String(c.optionId ?? '00').padStart(2, '0');
  const color = c.colorId || '000';
  return `${model}${year}${season}-${material}${option}-${color}`;
}

/** Année : 2 derniers chiffres de l'année saisie ("2026" -> "26"). */
export function deriveYearId(yearInput: string | number): string {
  const digits = String(yearInput).replace(/\D/g, '');
  return digits.slice(-2).padStart(2, '0');
}

/** Saison : Hiver/Automne ou commence par H -> "H" ; Été/Ete/Printemps ou commence par E -> "E". */
export function deriveSeasonId(text: string): 'H' | 'E' {
  const t = (text || '').trim().toLowerCase();
  if (/hiver|automne/.test(t) || t.startsWith('h')) return 'H';
  if (/[ée]t[ée]|ete|printemps/.test(t) || t.startsWith('e')) return 'E';
  return 'H';
}

/** Matière globale : "Exceptionnel"/"Exotique" -> "CE" ; sinon (cuirs classiques) -> "CU". */
export function deriveMaterialPrefix(name: string): 'CE' | 'CU' {
  return /exceptionnel|exotique/i.test(name || '') ? 'CE' : 'CU';
}

/**
 * Prochain ID séquentiel pour un préfixe (modèle "AA", matière "CU"/"CE"), sur `width` chiffres.
 * Ex. nextSequentialId(["AA007"], "AA") -> "AA008".
 */
export function nextSequentialId(existingIds: string[], prefix: string, width = 3): string {
  const re = new RegExp(`^${prefix}(\\d{${width}})$`, 'i');
  let max = 0;
  for (const id of existingIds) {
    const m = id.match(re);
    if (m) max = Math.max(max, parseInt(m[1], 10));
  }
  return prefix.toUpperCase() + String(max + 1).padStart(width, '0');
}

/**
 * Prochaine couleur (3 chiffres) en IGNORANT le code historique 999 (Noir, réservé)
 * pour ne pas générer "1000".
 */
export function nextColorId(existingIds: string[]): string {
  let max = 0;
  for (const id of existingIds) {
    const n = parseInt(id, 10);
    if (!Number.isNaN(n) && n !== 999) max = Math.max(max, n);
  }
  return String(max + 1).padStart(3, '0');
}

/**
 * Calcule le prochain code d'une catégorie de référentiel à partir des codes existants.
 * Détecte automatiquement un préfixe alphabétique (ex. modèles "AA", matières "CU") et la
 * largeur numérique, puis incrémente le plus grand numéro. Codes purement numériques
 * (couleurs) → prochain entier zero-paddé (ignore 999, réservé au Noir).
 * `prefixHint` force un préfixe (ex. "CE" pour matière exceptionnelle, "" pour numérique).
 * Restaure le comportement V1 : l'ID est CALCULÉ, jamais saisi en texte libre.
 */
export function nextRefCode(existingCodes: string[], prefixHint?: string): string {
  const codes = existingCodes.map((c) => (c || '').trim().toUpperCase()).filter(Boolean);
  const numericOnly = codes.length > 0 && codes.every((c) => /^\d+$/.test(c));

  // Détermine le préfixe alpha : hint explicite, sinon le plus fréquent parmi les codes.
  let prefix = prefixHint != null ? prefixHint.toUpperCase() : '';
  if (prefixHint == null && !numericOnly) {
    const freq = new Map<string, number>();
    for (const c of codes) {
      const p = c.match(/^[A-Z]+/)?.[0] ?? '';
      if (p) freq.set(p, (freq.get(p) ?? 0) + 1);
    }
    prefix = [...freq.entries()].sort((a, b) => b[1] - a[1])[0]?.[0] ?? '';
  }

  // Largeur numérique = max des longueurs de la partie chiffrée (plancher à 3).
  const re = new RegExp(`^${prefix}(\\d+)$`);
  let max = 0;
  let width = 3;
  for (const c of codes) {
    const m = c.match(re);
    if (!m) continue;
    width = Math.max(width, m[1].length);
    const n = parseInt(m[1], 10);
    if (n !== 999) max = Math.max(max, n);
  }
  return prefix + String(max + 1).padStart(width, '0');
}

// ─── Générateur d'ID référentiel — RÈGLES EXACTES de la V1 (legacy-v1/public/app.js) ─────
// Reproduit fidèlement le moteur d'ID éprouvé en production V1 (configPrefixMap +
// skuCategoriesConfig + autoGeneratedCategories), pour une parité V1↔V2 complète.

/** Préfixe 3 lettres par catégorie (V1 configPrefixMap). */
const REF_PREFIX: Record<string, string> = {
  models: 'MOD', years: 'ANN', seasons: 'SAI', options: 'OPT', optionTypes: 'TYP',
  colors: 'COU', sizes: 'TAI', globalMaterials: 'MGL', materials: 'MAT', skinTypes: 'TDP',
  linings: 'DOU', materialDetails: 'DMA', suppliers: 'FOU', jewelry: 'BIZ', origins: 'PAY',
  hsCodes: 'CHS', ateliers: 'ATE',
};
/** Catégories à ID auto « PREFIX-### » (V1 autoGeneratedCategories). */
const AUTO_GEN = new Set(['materials', 'skinTypes', 'linings', 'materialDetails', 'suppliers', 'jewelry', 'origins', 'hsCodes', 'ateliers']);
/** Règles de codification SKU par catégorie (V1 skuCategoriesConfig). */
const SKU_RULE: Record<string, { type: string; prefix?: string; pad?: number; ignoreMax?: number }> = {
  models: { type: 'prefix_seq', prefix: 'AA', pad: 3 },
  years: { type: 'last_two' },
  seasons: { type: 'season_logic' },
  options: { type: 'seq', pad: 2 },
  optionTypes: { type: 'seq', pad: 3 },
  colors: { type: 'seq', pad: 3, ignoreMax: 900 },
  sizes: { type: 'seq', pad: 2 },
  globalMaterials: { type: 'global_mat_logic' },
};

/**
 * Calcule le prochain ID d'une entrée référentiel selon les règles V1 (fidélité prod).
 * @param category catégorie (models, colors, suppliers…)
 * @param name libellé saisi (nécessaire pour years/seasons/globalMaterials)
 * @param existing codes déjà présents dans la catégorie
 */
export function generateRefId(category: string, name: string, existing: string[]): string {
  const ids = existing.map((s) => (s || '').trim()).filter(Boolean);
  const label = (name || '').trim();

  // Catégories à ID auto : PREFIX-### (max + 1).
  if (AUTO_GEN.has(category)) {
    const prefix = REF_PREFIX[category] ?? 'CFG';
    let max = 0;
    for (const id of ids) {
      if (id.toUpperCase().startsWith(prefix + '-')) {
        const n = parseInt(id.slice(prefix.length + 1), 10);
        if (!Number.isNaN(n) && n > max) max = n;
      }
    }
    return prefix + '-' + String(max + 1).padStart(3, '0');
  }

  const rule = SKU_RULE[category];
  if (!rule) return String(ids.length + 1).padStart(2, '0'); // fallback V1

  if (rule.type === 'last_two') {
    const m = label.match(/\d{4}/);
    return m ? m[0].slice(-2) : label.slice(-2).toUpperCase();
  }
  if (rule.type === 'season_logic') {
    const l = label.toLowerCase();
    if (/hiver|automne/.test(l) || l === 'h') return 'H';
    if (/[ée]t[ée]|ete|printemps/.test(l) || l === 'e') return 'E';
    return (label.charAt(0) || 'H').toUpperCase();
  }
  if (rule.type === 'global_mat_logic') {
    const prefix = /exceptionnel|exotique/i.test(label) ? 'CE' : 'CU';
    let max = 0;
    for (const id of ids) {
      const u = id.toUpperCase();
      if (u.startsWith(prefix)) {
        const n = parseInt(u.slice(prefix.length), 10);
        if (!Number.isNaN(n) && n > max) max = n;
      }
    }
    return prefix + String(max + 1).padStart(3, '0');
  }
  // seq / prefix_seq
  const prefix = (rule.prefix ?? '').toUpperCase();
  const limit = rule.ignoreMax ?? Infinity;
  let max = 0;
  for (const id of ids) {
    let s = id.toUpperCase();
    if (prefix) {
      if (!s.startsWith(prefix)) continue;
      s = s.slice(prefix.length);
    }
    const n = parseInt(s, 10);
    if (!Number.isNaN(n) && n > max && n < limit) max = n;
  }
  return prefix + String(max + 1).padStart(rule.pad ?? 1, '0');
}
